# DS8004: MLP Lab

## Backpropagation with Multiple Outputs

Implement the backpropagation algorithm for a given dataset. The algorithm is provided below, and can also be found in lecture notes and Figure 11.11 in the book.

![Backpropagation Algorithm](https://i.ibb.co/crKFJjB/Backpropagation-Alg.png)

![Sigmoid_Function](https://i.ibb.co/NKTCp41/sigmoid-func.png)

![Multilayer perceptron](https://i.ibb.co/Tvd79sr/multilayer-perceptron.png)

## Data preparation

In [2]:
# Define hyper-parameters and other size
N=30 # number of samples
K=3  # the number of classes
D=4  # size of dimension OR number of independent variables
H=10 # size of hidden layer

import numpy as np
import math

np.random.seed(42)
# X is input samples
X=np.round(np.random.rand(N,D),2)
# R is the output
R=np.repeat([[1,0,0], [0,1,0], [0,0,1]],10, axis=0)

# Adding some pattern into X
X[:10,:] = X[:10,:]*40
X[10:20,:] = X[10:20,:]*10

#Initialize all v ih and w hj to rand(−0.01, 0.01)
np.random.seed(100)    
w = np.random.uniform(-0.01,0.01,(D+1,H))
v = np.random.uniform(-0.01,0.01,(H+1,K))

#Adding Ones to the X as first bias input
X=np.c_[np.ones(30), X]

print(np.round(X))

[[ 1. 15. 38. 29. 24.]
 [ 1.  6.  6.  2. 35.]
 [ 1. 24. 28.  1. 39.]
 [ 1. 33.  8.  7.  7.]
 [ 1. 12. 21. 17. 12.]
 [ 1. 24.  6. 12. 15.]
 [ 1. 18. 32.  8. 20.]
 [ 1. 24.  2. 24.  7.]
 [ 1.  3. 38. 39. 32.]
 [ 1. 12.  4. 27. 18.]
 [ 1.  1.  5.  0.  9.]
 [ 1.  3.  7.  3.  5.]
 [ 1.  6.  2. 10.  8.]
 [ 1.  9.  9.  6.  9.]
 [ 1.  1.  2.  0.  3.]
 [ 1.  4.  3.  8.  4.]
 [ 1.  3.  5.  1.  8.]
 [ 1.  1. 10.  8.  2.]
 [ 1.  0.  8.  7.  7.]
 [ 1.  8.  1.  4.  1.]
 [ 1.  1.  1.  0.  0.]
 [ 1.  0.  0.  1.  1.]
 [ 1.  1.  0.  0.  1.]
 [ 1.  1.  1.  1.  0.]
 [ 1.  1.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.]
 [ 1.  1.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  0.  1.  1.]]


## Backpropagation algorithm implementation

In [ ]:
import math

# See Fig 11.11 for the pseudocode

def back_prop(x,r,H,K,D,step_size,accuracy_stop,iterations):
    '''
    Your code should be below
    '''
    
    return 0 # change return value if needed